# Generated by Django 3.0.7 on 2020-06-19 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200619_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstproduct',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='trxproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
