# Generated by Django 3.0.7 on 2020-06-20 06:14

from django.db import migrations, models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200619_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRXProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20, serialize=False)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mst_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.MSTProduct')),
            ],
            options={
                'unique_together': {('mst_product', 'color')},
            },
        ),
    ]
