# Generated by Django 3.0.7 on 2020-06-20 06:37

from django.db import migrations, models
import django.db.models.deletion
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200620_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxproduct',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trxproduct',
            name='mst_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='database.MSTProduct'),
        ),
        django_db_constraints.operations.AlterConstraints(
            name='trxproduct',
            db_constraints={'quantity_not_negative': 'check (quantity>=0)'},
        ),
    ]
