# Generated by Django 3.0.7 on 2020-06-19 08:39

from django.db import migrations, models
import django_db_constraints.operations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trxproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
        django_db_constraints.operations.AlterConstraints(
            name='mstproduct',
            db_constraints={'price_above_zero': 'check (price>0)'},
        ),
        django_db_constraints.operations.AlterConstraints(
            name='trxproduct',
            db_constraints={'quantity_not_negative': 'check (quantity>=0)'},
        ),
    ]
