# Generated by Django 3.0.7 on 2020-06-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200619_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxproduct',
            name='mst_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='database.MSTProduct'),
        ),
    ]
